// ---------- DM openers by kind ----------
const DMO={
thanks:["[hi|hello|hey]. [I know you probably won't see this but|sorry to message out of nowhere but] [thank you for|just wanted to say thanks for] {B}. [It meant a lot|I didn't expect to love it this much]",
 "[just wanted to say|had to say] thank you. {C} [is the reason I started reading again|made me start reading again] after [years|a long gap]",
 "[quick thank you|small thank you] from [{loc}|a stranger on the internet] for {B}. [that's all|no need to reply]"],
loreQ:["[hi sorry|hey!] [quick lore question|I know you get a lot of these|this might be a dumb question]: {CLAIM}? [I won't tell anyone|I've been arguing with my friend about it]",
 "[hello|hi] {A}, [I hope this isn't a bother|sorry if this is annoying]. {CLAIM}? [I couldn't find a straight answer anywhere|it's been bugging me for weeks]",
 "[random question|serious question, sorry]: [{QK}]? [genuinely can't stop thinking about it|my reading group is split]"],
advice:["[hi|hey]. [I'm writing my first novel|I've been stuck on a draft for months] and [I'm not sure how to|I keep failing to] [finish the second act|keep a big cast straight|write a believable villain]. [any advice|how did you start]?",
 "[hello|hi there]. [how do you deal with|any tips on] [rejection letters|self-doubt|writing every day]? [I'm a {job}|I only have an hour a night] and [I'm not sure it's worth it|I keep quitting]"],
helped:["[sorry if this is weird but|I don't usually message people but] your books got me through a really rough [year|winter|stretch]. [I just wanted you to know|that's all]",
 "[I'm not sure how to say this|this is hard to type], {B} was the [only thing|one thing] I could read [in hospital|after my dad died|after I moved here]. [thank you|that's it, thank you]"],
excited:["[OMG|oh my god|HI] [I can't believe I'm actually messaging you|I'm shaking typing this]. [I've read {B} {n3} times|{C} is my whole personality]!!",
 "[ok|okay] [I'm trying to be normal|deep breath]. [hi|hello]. [I love your work|I love {B}] [so much|more than is reasonable]. [that's it|okay bye]"],
nervous:["[hi|um hi]. [sorry|so sorry] [to bother you|if this is weird]. [I wasn't going to send this|I typed this three times]. [I just|I wanted to] [say hi|say I love the {P} chapters]",
 "[hello|hi], [I'm really nervous|this is my first time messaging an author]. [do you ever read these|is it okay if I ask something]?"],
writing:["[hi|hey] {A}! [I'm {age} and|I'm a {job} and] [I want to write fantasy|I'm trying to write a series like yours]. [how do you plan a world this big|do you map first or write first]?",
 "[hello|hi], [any advice for|how do you approach] [first drafts|worldbuilding|keeping continuity across books]? [no pressure|I'd really appreciate anything]"],
theory:["[hi|hello|hey!] [I think I figured something out|I have a theory]: {CLAIM}. [am I right|can you at least tell me if I'm warm|you don't have to answer]",
 "[ok|okay] [don't confirm anything but|please don't spoil it but] [{CLAIM}|I think {CLAIM}]. [am I close|just blink twice]"],
signed:["[hi|hello|hey]. [do you do|is there any way to get] signed copies? [I'm buying one for my sister|it's for my birthday|I'd happily pay shipping]. [no worries if not|ignore this if it's not possible]",
 "[hello|hi]! [random request|sorry to ask]: [would you ever sign|can I send in] [my copy of {B}|a bookplate]? [it's falling apart from rereads|it's a gift]"],
chat:["[hey|hi]. [how's your day going|how's the writing|did you sleep okay]?",
 "[that photo you posted|your last post] [looked insane|made me laugh|made me hungry]. [what is that|where was that taken]?",
 "[do you actually read all these comments|do you ever look at the replies]? [genuine question|I always wonder]",
 "[did you ever finish|how did you get on with] [that game you mentioned|that show you were watching|your reading list]?",
 "[I'm procrastinating|bored at work]. [what are you up to|tell me something about your day]?",
 "[random|unrelated]: [what are you drinking|what's the weather like there|what are you listening to while you write]?"],
critic:["[Hello|Hi]. I'm [a reviewer|writing a piece] on [{B}|your series]. [I wasn't kind about the ending|I have some reservations about the {P} arc]. [I hope that's okay|I wanted you to hear it from me]. [Would you like to respond|Happy to be corrected on anything]?",
 "[I'll be honest|Straight up]: [I think the last book undercut the first two|{C}'s arc doesn't hold]. [I'm publishing next week|my review goes up Friday]. [Any comment|Want to push back]?"],
author:["[hey|hi] [from one author to another|it's {AU}]: [loved|just finished] {B}. [we should talk shop|coffee at the next festival]?",
 "[hi|hello] {A}, {AU} here. [your {P} chapters|the way you handle {F}] [made me jealous|stuck with me]. [would you ever want to do a joint event|any chance of a blurb exchange]?",
 "[I'll be blunt|ok honestly]: [people keep comparing us|the comparison threads are brutal]. [no hard feelings|I think we should say hello]."],
journalist:["[Hello|Hi] {A}, I'm [a reporter|an editor|a features writer] at {outlet}. [We're working on|I'm putting together] a piece on [the fandom around {B}|your series]. [Would you be open to|Do you have time for] a [short interview|few questions]?",
 "[Hi|Hello]. {outlet} here. [We saw the reaction to|We noticed the buzz around] your latest post. [Any comment|Care to elaborate]?"],
publisher:["[Hello|Hi] {A}. [Mira from|This is a message from] {pub}. [We'd love to talk about|We're interested in discussing] [a special edition of {B}|a new multi-book deal|translation rights]. [Are you open to a call|Do you have an agent we should contact]?",
 "[Hi|Hello], {pub} here. [Sales on {B} have been [strong|climbing]|The numbers on {B} surprised us]. [Would you consider|We'd like to propose] [a tour|an anniversary edition|a short companion volume]?"],
celeb:["[hey|hi] {A}. [I'm {celeb}|{celeb} here]. [I read {B} on a flight and couldn't put it down|someone gave me {B} and I'm hooked]. [would you mind if I mentioned it|any chance of a chat]?",
 "[hi|hello], {celeb} here. [I've been telling everyone about {C}|I'm obsessed with {B}]. [could I post about it|are you open to a conversation about an adaptation]?"],
veteran:["[hey|hi] {A}. [I've been following you since|I've been here since] [your first book|{B}|before you had a verified tick]. [just wanted to say hi|I still have my first printing]. [how are you holding up with all of this|it's wild watching you grow]",
 "[hello|hi] again. [it's been|it's been a while]. [thinking of you|just checking in] after [{ago}|everything]. [no need to reply|I know you're busy]"]
};
// ---------- DM replies by class of the author's message ----------
const DMR={
warm:["[oh my god|wow|ok I'm not okay]. [you replied|thank you for answering]. [I'll treasure this|that made my week]","[that's so kind|you're lovely|thank you]. [I didn't expect an answer|I'm smiling at my phone like an idiot]","[ahh|aww]. [you're so nice|thank you]. [I'll go tell my friends I'm not insane|I'll stop being weird now]"],
yes:["[YES|I KNEW IT|OH]. [I'm screaming|I need to lie down|my friend owes me ten dollars]","[wait|hold on], [really|so I was right]? [I'm going to reread everything|I can't believe it]","[that changes everything|ohhh that makes so much sense now]. [thank you for telling me|I won't spoil it]"],
no:["[oh|ah|hm]. [okay|so I was wrong]. [I was so sure|well that's back to the drawing board]","[no?|really no?] [ok|alright]. [my whole theory just collapsed|I need a new theory]","[fair|fine]. [I'll admit I'm a bit crushed|I'll keep guessing]. [thank you for being honest|at least I know]"],
refuse:["[of course you'd say that|ha, fair|I figured]. [I'll keep guessing|that's basically a yes, right]","[no spoilers, I get it|understood]. [I'll wait like everyone else|you're allowed to be mysterious]","[haha okay|fine]. [I read that as a yes|I'll take it as a maybe]"],
thanks:["[no no, thank YOU|stop, you're making me emotional|thank you for existing as an author]","[that's the nicest thing|you really didn't have to]. [I'll go cry now|I'm keeping this]"],
question:["[honestly|pretty good actually|kind of tired]. [I'm a {job} so|work was {mood}]. [{hobby} is what's keeping me sane|I'm mostly trying to get through the week]","[ha, good question|let me think]. [I'm {mood} today|today was {mood}]. [mostly {hobby}|I've been into {hobby} lately]. [you?|what about you?]","[{mood}, to be honest|can't complain]. [{pet} woke me at five|{show} was on in the background]. [how about you|how's the writing]?"],
offer:["[WHAT|no way|I'm actually crying]. [yes please|that would be incredible|I don't know what to say]","[ok I'm shaking|oh my god]. [thank you thank you thank you|I'll send my address|I owe you everything]"],
rude:["[oh|ok]. [sorry for bothering you|I didn't mean to upset you|wow]. [I'll go|that wasn't very nice]","[that was uncalled for|ouch|didn't expect that from you]. [I'll leave you alone|forget I messaged]"],
short:["[ha okay|got it|ok thanks]. [I'll let you get back to it|sorry to take your time]","[haha|ok|alright]. [appreciate the reply|that's more than I expected]"],
long:["[wow|that's so much more than I expected]. [I'm saving this|I'm going to read this three times|thank you for taking the time]","[this is a lot of effort|I can't believe you wrote all this]. [thank you|I'm screenshotting it for my notes]"],
follow:["[anyway|also|oh and], [what was the hardest chapter|do you ever get tired of the questions|what's your favourite thing you've written]?","[sorry|random], [can I ask|one more thing]: [do you reread your own books|do you ever disagree with the fans]?","[ha, my {pet} just walked across the keyboard|I've been typing for ages]. [anyway|so], [what's next|what are you working on]?"],
sign:["[I'll let you get back to writing|I won't take any more of your time]. [thank you again|really, thank you]","[ok I should stop|sorry for the essay]. [have a good night|take care of yourself]"],
// non-fan kinds
journalist_yes:["[Wonderful|Great]. [I'll send questions over|I'll write something up]. [The piece should run in a few days|Expect it shortly]."],
journalist_no:["[Understood|Fair enough]. [We'll note that you declined to comment|We'll say you weren't available]. [Thanks anyway|The door's open]."],
publisher_yes:["[Excellent|Great to hear]. [We'll draw something up|I'll loop in our team]. [Sales will be thrilled|This will be a big one]."],
publisher_no:["[Understood|No problem]. [The offer stays open|We'll keep the conversation going]."],
author_yes:["[Brilliant|Love it]. [I'll tell my editor|Let's plan something]. [Drinks on me|Our readers will lose their minds]."],
author_no:["[Fair enough|No worries]. [I respect that|The offer stands]. [Still a fan, even if you're a rival|See you at the next festival]."],
celeb_yes:["[Amazing|That's great]. [I'll post tonight|My team will be in touch]. [Your readers are going to love this|Watch your inbox]."],
celeb_no:["[Understood|Fair enough]. [I'll just keep reading|No hard feelings]."],
critic_yes:["[Thank you for being gracious|I appreciate the response]. [I'll include your reply|You've given me something to think about]."],
critic_no:["[Understood|Fair]. [The review runs as planned|I'll let the piece speak]."]
};
const MOODS=['rough','fine','long','chaotic','slow','oddly good','exhausting','boring'];
// ---------- fan post templates (author-agnostic) ----------
const FP={
theory:["THEORY [THREAD|DROP|TIME]: {CLAIM}. [Here's my evidence|Receipts below|Hear me out]: [{P} in book {N}|chapter {ch}|{O}]. [Tell me I'm wrong|Please tell me I'm not insane]",
 "[Okay|ok|so] I've [been up all night|spent my weekend|made a spreadsheet] and I'm convinced: {CLAIM}. [{C} never denies it in chapter {ch}|The {P} scene makes no sense otherwise|{F} benefits too much]",
 "[Why nobody talks about|The case for] the idea that {CLAIM}. [A thread|Long post] [🧵|]"],
art:["[finally finished|drew|painted] [{C}|{C2}|{P}]. [took me|this took] [three weeks|forever|an embarrassing number of hours] [and a lot of tea|and I regret nothing]",
 "[my take on|fan art of] {C} [in the {P} scene|after the Collapse|at the end of book {N}]. [feedback welcome|the hands were a nightmare]",
 "[sketch dump|doodles]: {C}, {C2}, and [a very serious {O}|too many cloaks]"],
meme:["[me|reader|{C}] [after|when] [chapter {ch}|{A} says 'no spoilers'|reading the {P} chapter] [💀|😭|]",
 "[nobody:|literally nobody:] {C}: [I have a plan|I'll handle it]. {C2}: [you do not|we're doomed]",
 "[the {P} tourism board|{F}'s recruitment poster|{C}'s decision-making] [be like|energy]"],
review:["[Review|Honest review]: {B} — [{r}/5|{r} stars]. [The {P} sequence|{C}'s arc|The {F} politics] [carried it|dragged it down|made it unforgettable], [though|but] [the ending|the middle|the pacing] [felt rushed|felt earned|didn't land for me]",
 "[{r}/5|{r} stars] for {B}. [Loved|Couldn't stand|Mixed on] {C}. [The prose is dense but rewarding|Too many names, not enough payoff|I'd read the {P} chapters again tomorrow]",
 "{B} [reread|review]: [on a second pass|this time], [{C} is|the {P} sections are] [far better|far worse] than I remembered. {r}/5"],
ranking:["[Ranking|Ranking every] [{B} character|major character] by [how likely they are to betray you|how much they ruined my week|who I'd trust with a secret]: [1. {C}  2. {C2}  3. {CF}|1. {CF}  2. {C}  3. {C2}]. [Fight me|No notes]",
 "[Tier list|My tier list]: [S: {C}|S: {C2}]. [A: {CF}|A: {C}]. [F: {CH}|F: {O}]. [Defend your faves|Argue below]"],
quote:["[This line|This quote|Page {pg}]: '{BQ}' [lives in my head|is my whole mood|got me]",
 "[favourite line|quote of the day|reading at 2am]: '{BQ}' [— {B}|]"],
ship:["[Reminder that|PSA:] {C} and {C2} [are in love|are endgame|are the heart of this series]. [Evidence thread|Receipts]",
 "[the {C}/{C2} edit|I made an edit]. [no notes|please be kind]. [the {P} scene|the last chapter of book {N}] [broke me|did this]"],
lore:["[Lore analysis|Deep dive]: [why {F}'s symbol appears in {P}|what the {O} actually is|how {F} and {C} connect]. [Long post incoming|Thread]",
 "[A quick lore note|Something I noticed]: [{P} is mentioned in book {N} and again in book {N2}|{QK}]. [that can't be a coincidence|has anyone else noticed this]"],
predict:["[Predictions for|My predictions for] [book {N}|the next book]: [1. {C} dies  2. {P} falls  3. {F} wins|1. {CLAIM}  2. {C2} survives  3. we cry]. [Screenshot this|Check back in a year]",
 "[Prediction|Hot take]: [{CLAIM}|{C} returns]. [Quote this post|If I'm wrong I'll delete my account]"],
timeline:["[I made a timeline|Timeline of everything we know] [of the Collapse|of {F}|of {P}]. [Corrections welcome|Let me know what I got wrong]. [{ev1}|{ev1}]",
 "[Full chronology|Chronology dump]: [{ev1}, then {ev2}|{ev2} comes before {ev1}]. [change my mind|someone check my maths]"],
criticism:["[Unpopular opinion|Hot take|Honest thoughts]: [the middle of book {N} is too long|{C} is overrated|the {P} arc undercuts the setup]. [I still love the series|and I'm tired of pretending]",
 "[Not hating but|Respectfully]: [{B} has a pacing problem|the twist about {C} cheapens the first book|the worldbuilding is doing the plot's job]"],
discussion:["[just finished|finished] {B}. [need to talk to someone|I have so many feelings|{C}?? {C2}??]",
 "[who else|is anyone else] [still thinking about|stuck on] [{P}|chapter {ch}|{C}]? [I can't sleep|please talk to me]",
 "[reading|rereading] {B} [on the train|in the park|at 2am]. [{C} just said the thing|I'm at the {P} chapter]. [wish me luck|send help]"],
passage:["[page {pg}|chapter {ch}]: [the line that broke me|the paragraph I keep rereading]. [no commentary|speechless]",
 "[annotated|my annotations] for [chapter {ch}|the {P} scene]. [highlighter casualties|so many tabs]"],
rumour:["[hearing|heard] [from a friend at the publisher|from someone in the trade|from a bookseller] that {RUM}. [take it with salt|no source, but still]",
 "[unconfirmed but|rumour:] {RUM}. [thoughts|discuss]"],
fan:["[found|spotted] {B} in the [wild|airport|charity shop]. [it's everywhere now|my local shop sold out]",
 "[bookshop haul|library haul]: {B}, plus [too many others|one I can't afford]. [tbr is cursed|worth it]"]
};
// ---------- other author post templates ----------
const AUP=["[Draft|Chapter {ch}|First pass] [done|finally done|is a monster]. [Time for tea|I need a nap|Don't talk to me]",
 "[Reminder|Gentle reminder] that [writing is mostly rewriting|first drafts are meant to be bad|nobody's book looked good at page 100]. [Keep going|Back to the desk]",
 "[Cover reveal|Cover reveal day]! [{ob}|my next book, {ob}] [is out|drops] [this spring|in autumn|next year]. [Pre-order|Link in bio]",
 "[Signing in|Reading in|Festival panel in] [{loc}|Edinburgh|Hay|Austin] [next month|this weekend]. [Come say hi|Bring a pen]",
 "[Hot take|Controversial]: [prologues are fine|maps in fantasy are essential|sequels are harder than debuts]. [Fight me|Argue below]",
 "[Currently reading|Just finished] [{AU2}|a debut I can't name yet] and [wow|it's so good|I'm jealous]. [Recommend away|Read it]",
 "[Deadline|Edits] [week|season]. [Send coffee|Pray for me]"];
const RUMOURS=["Book {N2} is going to be adapted for television","the next book will be set entirely in {P}","{C} is getting a spin-off novella","the author has already finished the last book of the series","{B} is being translated into eleven languages","the publisher is pushing the next release back a year","{C} dies in the next book","{F} isn't what we think it is and the author is hiding it","a film studio has just bought the rights to {B}","the author is leaving their publisher","{O} is the key to the whole series and it's on the cover","there will be a prequel about the Collapse"];
// ---------- news headline templates ----------
const NEWS={
review:["Review: {B} [dazzles|divides|is dense but rewarding]","[The {B} verdict|Why {B} is the fantasy event of the year|Our review of {B}]","{A}'s [latest|newest] [thrills|frustrates|surprises]: a review of {B}"],
interview:["[An interview with|In conversation with|Talking secrets with] {A}","{A} on [{C}|worldbuilding|why {B} took so long]","[Q&A|Interview]: {A} [opens up|keeps her secrets|refuses to spoil]"],
ranking:["[The ten best|Ranking the] [characters|villains|cliffhangers] in {B}","Fantasy [rankings|power rankings]: [{A}|{B}] [climbs|enters the list] at No. {rk}","Which {B} character [would survive|is most likely to betray you]? Readers vote"],
controversy:["[Fan backlash|Readers split|Debate erupts] [over|after] {A}'s [latest post|silence|comments]","[Is {A} baiting fans|Too many teasers?]: [the case against|the case for] the {B} [marketing|hype cycle]","[Delay|Controversy|Row] [over|around] {B}: [what we know|what readers are saying]"],
release:["{B} [arrives|lands|is out]: [what to expect|everything we know|the reviews so far]","[Bookshops brace for|Queues expected for|Release week for] {B}","{B}: [launch date confirmed|release date set|pre-orders surge]"],
industry:["[Publishing|Industry] [notes|roundup]: {A}'s [sales|{B}] [climb|top the charts|hold steady]","{pub} [expands|doubles down on|reprints] {A}'s [series|backlist]","[Sales|Charts]: {B} [enters|climbs|tops] the [bestseller list|hardcover chart]"],
theory:["Fans think they've cracked [the {M} mystery|{A}'s biggest secret]","[The theory that's taking over|Inside the fan theory about] {C} and {C2}","[Everyone is talking about the idea that|Why readers believe that] {CLAIM}"],
leak:["[Leaked|Alleged leak]: [a page from|the cover of|a chapter title from] {B2} [circulates|surfaces online]","[Did {A} just reveal|Accidental reveal?]: [fans notice|readers spot] [a slip|a detail] in a post"],
award:["{B} [shortlisted for|wins|nominated for] {award}","[{A}|{B}] [takes|is up for] {award}: [the full list|reaction]"],
rare:["[A major celebrity|A well-known actor|A famous musician] [says they're reading|is hooked on] {B}","[Book club pick|Reading list]: {celeb} [names|picks] {B}"]
};
